### ISSUE TITLE
실습 2주차 (1) 이메일 로컬파트 문법의 특수문자 사용 여부에 대하여

### ISSUE THREAD

**Issue by bjs0107** [CNUCOM/compilers_CNU_2023#10]
컴퓨터융합학부 20학번 배준서입니다.
 
메일로 TA분께 보냈지만 다른 학생분들에게도 여쭤보고 싶어 올립니다.
2주차 실습(1)에서 이메일의 입력 조건이 도메인 파트만 기술되어 있고,
로컬파트(사용자명@) 부분에 특수문자 가능 여부에 대해 설명을 들었던 것 같은데, 기억이 모호하여 여쭤봅니다.
 
또한 만약 사용가능하다면, 이메일의 정규표현식 구현을 위해 위키백과의 전자 우편 주소 문법을 참고할 생각입니다.
[[전자 우편 주소 - 위키백과, 우리 모두의 백과사전 (wikipedia.org)]](https://ko.wikipedia.org/wiki/%EC%A0%84%EC%9E%90_%EC%9A%B0%ED%8E%B8_%EC%A3%BC%EC%86%8C)
그런데 아무래도 다른 입력 정규표현식에 차원이 다른 구현 난이도라, 의도한 바가 맞는지 궁금합니다.

**Comment by VertexToEdge** [comment]
전에 유저 인풋 벨리데이션을 구현하면서 조사를 했었는데,
완벽한 email regex를 만드는건 허상이라는 결론을 지었습니다.


https://emailregex.com/index.html
https://www.regular-expressions.info/email.html
가령 rfc 5322에 기반해서 이메일 패턴 매칭을 한다는 위 정규표현식들도 이걸 완벽하다는 증명을 할 수 없을 뿐더러,
여타 이메일 서버들이 rfc 5322에 기반해서 메일 서비스를 제공한다는 보장도 없습니다.
rfc가 구현에 있어서 강제 사항이 아니기 때문입니다.
당연하게도 공식 규격에 맞지 않는 이메일 패턴이 언제든지 생겨날 여지가 있겠죠.

따라서 현실의 모든 이메일 패턴을 매칭하는 정규표현식 보다는,
주어진 조건(과제에서 제시된 요구사항)에 충실한 정규표현식을 짜는게 생산적이지 않나... 라는 생각이 듭니다. 어짜피 불가능한거니까요.
조교님들께서 극한의 엣지케이스를 넣진 않으시겠지만 그런 엣지 테스트 케이스가 존재해서 점수가 깎이면 뭐 어쩔 수 없는거 아닐까요 ㅋㅋ

**Comment by bjs0107** [comment]
오호... 그런 조사 결과도 있었군요. 확실히 일리가 있는 결론입니다. 아무래도 주어진 조건만 잘 만족하게 구현하는게 확실히 생산적인 활동으로 이어질 것 같긴 합니다. 좋은 답변 감사합니다. :)
