### ISSUE TITLE
실습 5주차 과제 질문입니다.

### ISSUE THREAD

**Issue by KastanEr** [CNUCOM/compilers_CNU_2023#13]
<img width="240" alt="스크린샷 2023-10-07 오후 9 35 43" src="https://github.com/CNUCOM/compilers_CNU_2023/assets/98243874/54ac2c29-a6bb-469a-9efd-5a2000b75dfa">

주어진 g4파일에  opt_paren 부분에서 공백이 포함되어있어

<img width="240" alt="스크린샷 2023-10-07 오후 9 36 06" src="https://github.com/CNUCOM/compilers_CNU_2023/assets/98243874/16f549ef-b040-4fc5-bfc4-5b65c3c03dc5">

이 파스트리처럼 c=a+b가 (a, opt_paren:1), (b, opt_paren:1)로 파싱이 됩니다. 혹시 오타인 건가요?

**Comment by Masterwhiece** [comment]
NAME이 단독으로 사용된 경우를 나타내기 위한 경우를 나타내기 위해 있는 문법입니다.
