### ISSUE TITLE
실습 5주차 관련 질문입니다.

### ISSUE THREAD

**Issue by Kim-jian** [CNUCOM/compilers_CNU_2023#14]
안녕하세요? 00분반 201902677 김지안입니다.
다름이 아니라 pdf에 올려주신 예제 코드
a=3
b=4
c=a+b
d=3-(4+5)
print c
f=sum(5,6)
def sum(a,b):
return a+b
def check20(a):
if a==20:
return (a+20)
else:
return (a-20)
print "Hello World"

-> 를 Antlr preview로 보면 def sum 다음에 개행 없이 def check20이 작성되었기 때문에 중첩 def문으로 판단합니다.
![image](https://github.com/CNUCOM/compilers_CNU_2023/assets/57202844/281eef86-f4a8-4d18-8898-bf16742f9665)
따라서 그 결과는 다음과 같이 됩니다.
![image](https://github.com/CNUCOM/compilers_CNU_2023/assets/57202844/5f60ba09-bcb4-4c18-9d5b-c34d6d03ae19)

만약 pdf p.6의 결과 화면 출력처럼 코드를 뽑아내려면 def, while 문과 같은 compount stmt의 끝에는 구별을 위해 개행문자를 집어넣어 구분을 해주어야하는 것 같습니다.
그러면 Antlr의 preview도 별개의 def로 인식하고 파스트리를 그리며
![image](https://github.com/CNUCOM/compilers_CNU_2023/assets/57202844/8e3f3433-40bb-419c-aa71-c4db25334f73)
다음과 같은 결과를 얻을 수 있게 되는 것 같습니다.
혹시 제가 놓치고 있거나 실수한 부분이 있으면 어떤 점을 잘못 접근하고 있는 것인지 여쭈어보아도 되겠습니까?

**Comment by PLASLaboratory** [comment]
안녕하세요 컴파일러 TA 이석수 입니다.
실습 자료에 있는 예시 코드의 결과는 학생 분께서 말씀해 주신대로
![image](https://github.com/CNUCOM/compilers_CNU_2023/assets/26050690/0f7904d3-afbe-4053-8d1d-65fe7b220a2b)

위와 같이 결과가 나와야 하는 것이 맞습니다.
해당 부분은 실습 자료가 잘못된 부분이 맞습니다.

해당 부분을 반영해서 추후 실습 자료 재 업로드 하겠습니다.

질문 감사합니다.

**Comment by Kim-jian** [comment]
빠른 답변 감사합니다!

201902677
김지안 올림.
-----Original Message-----
