### ISSUE TITLE
5주차 실습 : tinyPythonBaseListener Interface 내의 visitTerminal 메소드 사용가능 여부 및 <EOF> 출력

### ISSUE THREAD

**Issue by OneEpitome** [CNUCOM/compilers_CNU_2023#18]
안녕하세요, 00분반 강일모입니다.

제목과 동일하게, tinyPythonBaseListener 에 정의된 visitTerminal 메소드를 사용해도 되는지 궁금합니다.

추가로, Pretty Print 결과 `<EOF>` 가 콘솔에 출력돼도 되는지 궁금합니다.

감사합니다.

**Comment by Masterwhiece** [comment]
사용하셔도 상관 없습니다. 하지만 해당 부분은 주석을 작성해주길 바랍니다.
EOF는 출력 대상이 아닙니다. 출력해야 하는 결과는 예쁘게 정렬된 "코드"입니다.

감사합니다.
