### ISSUE TITLE
중간고사 공지

### ISSUE THREAD

**Issue by Masterwhiece** [CNUCOM/compilers_CNU_2023#19]
안녕하세요. 01분반 TA 노유정입니다. 🙂

컴파일러개론 중간고사를 공지합니다.
시험 일시는 이전에 교수님께서 안내해주신 대로 10/27일 금요일의 본래 수업시간 입니다.
하지만 이외 잘 확인해야 하는 디테일이 많으니 공지를 꼼꼼하게 읽고 숙지하기 바랍니다.

## 시험 일시 및 장소
- **00 분반** : 10월 27일 금요일, 오전 9:30-11:00, 411호
00 분반에 한하여 조기 퇴실 불가능 (시험 문제 유출 방지) 
시험지와 답안지 모두 제출한 경우, 종이 자료에 한하여 다른 과목 시험 공부 허용 (자기 자리에서, 혼자, 조용히)
- 01 분반 : 10월 27일 금요일, 오전 11:00-12:30, 412호

## 입실 시간
- 00 분반 : 9:20-9:30, 10분간
- **01 분반** : 10:50-11:00, 10분간
01 분반에 한하여, 11시 이후 입실 불가능 (시험 문제 유출 방지)

## 기타 안내사항
- 시험을 위한 컨닝 페이퍼 사용 가능
  - A4 반장 사이즈 양면
  - 학번, 이름 기재
  - 수기 작성 (출력물 허용 안함)
  - 시험 종료 후 제출 받을 예정 → 즉, 사이즈, 수기 작성 등의 규칙 지키지 않은 학생 확인할 예정
- 10월 26일부터 질문 불가능 (교수님, TA 모두)
- 시험 중 전자기기 사용 금지
  - 휴대폰, 스마트 워치, 태블릿, 무선 헤드셋 등 모든 전자기기 사용을 금함
  - 소지 시, 시험 중 전원 끄고 가방에 넣기

학생 여러분들 시험 공부, 중간고사 모두 파이팅입니다.

**Comment by Jeongmingyeong** [comment]
안녕하세요 202102699 정민경입니다.

A4 반장 사이즈의 양면 컨닝페이퍼를 허용하신다고 하셨는데 A4 사이즈 단면 컨닝페이퍼를 사용해도 될까요?

**Comment by Masterwhiece** [comment]
@Jeongmingyeong 
A4 종이를 반으로 자른 상태의 종이만 허용합니다.

**Comment by Jeongmingyeong** [comment]
> @Jeongmingyeong A4 종이를 반으로 자른 상태의 종이만 허용합니다.

감사합니다!

**Comment by PLASLaboratory** [comment]
안녕하세요 TA 이석수 입니다.
컨닝페이퍼 관련하여 추가 설명 드립니다.
A4 한 장 사이즈가 안되는 이유는 옆이나 뒤에서 볼 수 있는 경우가 존재하기 때문입니다.
번거롭더라도 A4 반장 사이즈를 꼭 지켜주시기 바랍니다.
