### ISSUE TITLE
5주차 과제에 대해 질문 드립니다. 

### ISSUE THREAD

**Issue by Sauter001** [CNUCOM/compilers_CNU_2023#21]
안녕하세요
![image](https://github.com/CNUCOM/compilers_CNU_2023/assets/54736876/d0c6cf97-3637-488a-aad0-847b9598f17e)
![image](https://github.com/CNUCOM/compilers_CNU_2023/assets/54736876/f425a93c-7656-4cc0-be6c-2e9151c86b8c)

예제 tpy 파일에는 포함 되어있지 않았지만 g4 파일에는 while문과 flow statement에 대한 문법도 포함되어 있는 걸 확인했습니다.
혹시 이것에 대한 부분도 구현해야 되는지 질문 드립니다. 만약 while문의 구현이 필요하다면 반복할 코드로 포함할 기준도 알고자합니다.

**Comment by Masterwhiece** [comment]
과제는 tinyPython.g4 문법을 기준으로 합니다.
실습 자료에서는 예시를 들어드렸을 뿐이고,
당연히 flow stmt, while도 당연히 구현하셔야 합니다.

**Comment by Masterwhiece** [comment]
추가로 while문 안에 들어가는 코드를 결정하는 기준은 NEWLINE 입니다.
실습 자료에 확인해보시면 설명 있습니다.

**Comment by Sauter001** [comment]
답변 감사합니다
