### ISSUE TITLE
umm 파일을 자바로 불러올 시 한글 깨짐 현상이 발생합니다.

### ISSUE THREAD

**Issue by choisieun** [CNUCOM/compilers_CNU_2023#4]
안녕하세요. 저는 01분반 최시은입니다.
제목 그대로 umm 파일을 자바로 가져온 후 파일을 읽으면 깨지는 현상이 발생합니다. 그래서 UTF-8로 변환을 하였으나 자바의 한글 문자열과는 다른 것인지 분명 같은 문자열임에도 불구하고 다른 문자열로 인식이 됩니다. 다른 분들은 이런 문제가 없는 것인지 궁금합니다. 지금도 최대한 해결방법을 모색하는 중입니다.
참고로 IDE는 VSCode를 사용 중입니다. InteliJ를 사용하니 umm 파일을 찾지 못하는 현상이 발생했습니다.

**Comment by VertexToEdge** [comment]
개발 환경에 대한 정보가 좀 더 필요할 것 같아요.
어떤 운영체제를 사용하시나요??

**Comment by choisieun** [comment]
관심 가져주셔서 감사합니다. 운영체제는 윈도우10을 사용중이고 프로그램을 돌릴 시 cmd를 사용합니다.

**Comment by Masterwhiece** [comment]
@choisieun 
먼저 Intellij에서 src 디렉토리 안 말고, project 디렉토리 안에 `.umm` 파일을 넣고, 실행해보시기 바랍니다.

**Comment by Masterwhiece** [comment]
@choisieun 
![image](https://github.com/CNUCOM/compilers_CNU_2023/assets/67138939/88c9beb4-3f64-40ee-a670-ddd81aa29f26)

**Comment by choisieun** [comment]
파일 옮기고 인텔리제이로 실행하니 한글이 안 깨지네요. 정말 감사합니다!
