### ISSUE TITLE
[엄어.]와 [엄.]은 왜 호출하는 변수가 차이가 나나요?

### ISSUE THREAD

**Issue by bjs0107** [CNUCOM/compilers_CNU_2023#5]
00분반 배준서 학생입니다.
실습자료 15페이지의 예제2를 보면...

[엄어.] 를 통해 **첫번째 변수**에 1을 더하는걸 볼 수 있는데,

9페이지의 [엄..]를 보면 동일하게 **첫번째 변수**에 2를 더한다고 적혀 있습니다.
비슷한 느낌으로 [어엄.]을 사용하면 **2번째 변수**에 1 대입이라는데, 이것이 [엄어.]와 무엇이 다르게 사용되는지 알고 싶습니다.

동일한 맥락으로 [어엄.]을 했을 때는 어떤 이유로 첫번째 변수로 매칭되는지 알고 싶습니다.

**Comment by PLASLaboratory** [comment]
안녕하세요 TA 이석수 입니다.

[엄] 은 변수를 대입하는 키워드 입니다.
[엄어.] 첫 번째 변수에 어라는 변수를 가지고와서 +1을 하는 것을 말합니다.

그래서 실습자료 15 페이지 예시의 C 코드에서는 _input 변수에 +1 을 증가시키는 것을 _input++; 로 표현했습니다.
해당 부분은 자유롭게 바꾸시면 됩니다.
++ 연산을 하던지 아니면 _input = _input+1 을 하시던지 자유롭게 작성하시면 됩니다.

실습자료 9페이지 같은 경우는
[엄..] 은 첫 번째 변수에 2를 대입하는 것을 말합니다.

[어엄] 은 2번째 변수를 가지고 오는 명령입니다.
따라서 [어엄.]은 2번째 변수에 1을 대입하는 명령입니다.

질문 감사합니다
