### ISSUE TITLE
변수 선언이 쉽지 않습니다..

### ISSUE THREAD

**Issue by inhyuk15** [CNUCOM/compilers_CNU_2023#6]
정말 오래 고민했는데

#include <stdio.h>
void main() {
int var1,var2,var3,var4,var5,var6,var7,var8,var9;
var1=3*3*3*3
printf("%c",var1);
return 0;
}

이런식으로
int var1,var2,var3,var4,var5,var6,var7,var8,var9;
을 미리 두고 변수의 개수가, 그러니까 어어어어어어어엄
제 코드는 이런 식에서 어의 개수가 9개 이하이길 바라는 코드가 되었습니다.

이 변수 선언을 어떻게 접근하면 좋을까요..?

+) 문법에 대해서 여쭤봅니다..
//      ****** Grammer ******
//    <program> ::= <assignment> | <outputChar> | <outputInt> | <input>
//    <assignment> ::= <var1> "엄" <integer>
//    <outputChar> ::= "식" <integer> "ㅋ"
//    <outputInt> ::= "식" <integer> "!"
//    <input> ::= <var1> "엄식?"
//    <integer> ::= <var2> | <multiplex>
//    <multiplex> ::= " " <integer>
//    <var2> ::= <var1> <incDec> | <var1> | <incDec>
//    <var1> ::= "어*"
//    <incDec> ::= <plusOne> | <minusOne>
//    <plusOne> ::= .+
//    <minusOne> ::= ,+
//      ****** Grammer ******

<img width="496" alt="스크린샷 2023-09-11 오후 12 41 33" src="https://github.com/CNUCOM/compilers_CNU_2023/assets/78422003/38d06ef2-e16e-4113-ada7-72d38ea57ec5">

이슈에는 태그를 넣으면 사라지네요. 수정하기를 누르면 확인할 수는 있는데 일단 스크린샷으로 찍어올립니다.

문법을 이런식으로 만들었습니다.
다만 연산자 우선순위라던지
일단 "엄식?" 이게 제일 길어서 좀 위쪽으로 올린 점은 있는데

사실 문법을 어떻게 만들어야할지 감이 안옵니다...

혹시 노하우를 가르쳐주실 수 있나요.

**Comment by VertexToEdge** [comment]
``` c
#include <stdio.h>
#include <wchar.h>
#include <locale.h>
int memory[100];
int main(){
  setlocale(LC_CTYPE, "");
  memory[0] = (1+1+1);
  wprintf(L"%d", (memory[0]+1+1+1+1) * (1+1+memory[0]+1+1+1+1));
  return 0;
}
```
저 같은 경우에는 엄랭에서 사용 할 변수를 배열로 선언하고, "어어엄" , "어어어" 같은 경우에 "어"의 개수로 인덱스를 구해서 배열에 접근하도록 만들었습니다.
이렇게 하면 사용 가능한 변수의 개수를 쉽게 확장할 수 있습니다.

다른 방법으로는 "어어엄"을 int aaa=0; 같은 식으로, "어어어"를 aaa라는 식으로 "어" 의 개수대로 변수 이름을 동적으로 생성하는 방법이 있겠습니다. 인코딩 방식을 좀 다르게 하면 index를 hex string으로 바꿔서 더 축약된 표현으로 바꿀 수 있을 것 같습니다.

2번째 방법의 경우에는 c언어 공식스펙 ISO 9899의 section 5.2.4.1에 따르면
![image](https://github.com/CNUCOM/compilers_CNU_2023/assets/37045096/0b6561fd-2643-447f-8803-dd73a1c379cd)
c 컴파일러에서 identifier는 최소한 63글자 까지는 지원해야 한다고 합니다. 따라서 어떤 컴파일러에서는 63번째 변수 이상으로 접근 하지 않을 가능성도 존재할 듯 합니다.

물론 대부분의 컴파일러에서 변수 길이에 딱히 제한을 두진 않지만 고려해볼만한 요소인 것 같아요.

**Comment by hi-jin** [comment]
저는 성빈님이 언급하신 것처럼, 미리 만들어놓지 않고 코드를 보고 필요한 변수를 선언하는 방식으로 풀었습니다.
예를 들어 한 줄씩 파싱할 때, 좌변에 변수가 나타나는 경우 (파싱 과정에서 "엄" 등장) 시작부터 "엄" 위치까지의 길이를 세고, 그 길이를 변수 넘버로 이용했습니다.

예를 들어, 어어엄. 이라 길이가 3이라면, 어어엄(대입에 사용될 때)과 어어어(값으로 사용될 때) var3 이라는 변수 이름을 사용하게 됩니다.

저는 Parser를 클래스로 구현했는데, Parser 클래스에 이런 "변수 넘버" (위 예제에서는 3)를 Set 자료구조에 저장하도록 했습니다.
최종적으로 모든 문장을 파싱 완료하면, Set 자료 구조에 저장된 변수 넘버를 순회하며 선언해주는 방식을 사용했습니다.

ex) 파싱 완료 후 동작 모습
1. #include <stdio.h>\n\nint main() {\n 삽입
2. Set을 순회하며 "int var" + Integer.toString(varNum) + ";"; 삽입
3. 이후 2행부터 (어떻게 제외) 파싱한 결과 출력

하는 방식으로 동작하도록 했습니다.
